# Generated by Django 3.1.2 on 2020-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201124_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='sid',
            field=models.CharField(max_length=8),
        ),
    ]
