# Generated by Django 3.1.2 on 2020-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201124_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.CharField(default='dsada@gmail.com', max_length=30),
        ),
    ]
