# Generated by Django 3.1.2 on 2020-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_alumno_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.CharField(default='dsada@gmail.com', max_length=50),
        ),
    ]
