# Generated by Django 3.1.2 on 2020-12-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201201_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumAsig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.asignatura')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.alumno')),
            ],
        ),
    ]
