# Generated by Django 3.1.2 on 2020-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20201203_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumasig',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
