# Generated by Django 3.1.2 on 2020-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alumasig_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='exp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
