# Generated by Django 3.1.2 on 2020-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alumno_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
