# Generated by Django 3.1.2 on 2020-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201221_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumasig',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
