# Generated by Django 3.1.2 on 2020-12-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alumasig_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumasig',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
