# Generated by Django 3.1.2 on 2021-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alumasig_nminima'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.IntegerField(default=-1)),
                ('uid1', models.CharField(max_length=30)),
                ('uid2', models.CharField(max_length=30)),
            ],
        ),
    ]
