# Generated by Django 3.1.2 on 2021-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20210105_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='career',
            field=models.CharField(max_length=50),
        ),
    ]
