# Generated by Django 3.1.2 on 2021-01-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210105_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grade',
        ),
    ]
