# Generated by Django 3.1.2 on 2021-01-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_remove_alumno_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='career',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='grade',
        ),
    ]
